       DATA DIVISION.
       FILE SECTION.

       WORKING-STORAGE SECTION.

       LINKAGE SECTION.
      * ---------------------------------------------------------------
      * DATA DIVISION:
      *    - ESTA DESTINADA PARA DEFINIR ARCHIVOS, REGISTROS Y CAMPOS
      *      QUE UTILIZARA EL PROGRAMA COBOL

      * ARCHIVO, REGISTRO Y CAMPO:
      *    - UN ARCHIVO PUEDE ESTAR DENTRO DE UN DISCO MAGNETICO Y 
      *      ESTE SE COMPONE DE UNO O VARIOS REGISTROS ...
      *    - UN REGISTRO SE COMPONE DE UNO O VARIOS CAMPOS

      * SECCIONES:
      *    - FILE SECTION
      *    - WORKING-STORAGE SECTION
      *    - LINKAGE SECTION